
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-04T20:55:17.062+01:00
 * Generated source version: 3.2.7
 *
 */
public final class IPlagiatonWCF_BasicHttpBindingIPlagiatonWCF_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "PlagiatonWCF");

    private IPlagiatonWCF_BasicHttpBindingIPlagiatonWCF_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PlagiatonWCF.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PlagiatonWCF ss = new PlagiatonWCF(wsdlURL, SERVICE_NAME);
        IPlagiatonWCF port = ss.getBasicHttpBindingIPlagiatonWCF();

        {
        System.out.println("Invoking setAvailableMethods...");
        java.lang.String _setAvailableMethods_project = "_setAvailableMethods_project-328195777";
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _setAvailableMethods_methods = new com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring();
        java.util.List<java.lang.String> _setAvailableMethods_methodsString = new java.util.ArrayList<java.lang.String>();
        java.lang.String _setAvailableMethods_methodsStringVal1 = "_setAvailableMethods_methodsStringVal-497840313";
        _setAvailableMethods_methodsString.add(_setAvailableMethods_methodsStringVal1);
        _setAvailableMethods_methods.getString().addAll(_setAvailableMethods_methodsString);
        java.lang.String _setAvailableMethods__return = port.setAvailableMethods(_setAvailableMethods_project, _setAvailableMethods_methods);
        System.out.println("setAvailableMethods.result=" + _setAvailableMethods__return);


        }

        System.exit(0);
    }

}
