package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-04T20:55:17.099+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IPlagiatonWCF")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IPlagiatonWCF {

    @WebMethod(action = "http://tempuri.org/IPlagiatonWCF/setAvailableMethods")
    @Action(input = "http://tempuri.org/IPlagiatonWCF/setAvailableMethods", output = "http://tempuri.org/IPlagiatonWCF/setAvailableMethodsResponse")
    @RequestWrapper(localName = "setAvailableMethods", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetAvailableMethods")
    @ResponseWrapper(localName = "setAvailableMethodsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetAvailableMethodsResponse")
    @WebResult(name = "setAvailableMethodsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String setAvailableMethods(
        @WebParam(name = "project", targetNamespace = "http://tempuri.org/")
        java.lang.String project,
        @WebParam(name = "methods", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring methods
    );
}
