package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-04T20:55:17.103+01:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "PlagiatonWCF",
                  wsdlLocation = "http://plagiaton-wcf.azurewebsites.net/PlagiatonWCF.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class PlagiatonWCF extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "PlagiatonWCF");
    public final static QName BasicHttpBindingIPlagiatonWCF = new QName("http://tempuri.org/", "BasicHttpBinding_IPlagiatonWCF");
    static {
        URL url = null;
        try {
            url = new URL("http://plagiaton-wcf.azurewebsites.net/PlagiatonWCF.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PlagiatonWCF.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://plagiaton-wcf.azurewebsites.net/PlagiatonWCF.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PlagiatonWCF(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PlagiatonWCF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlagiatonWCF() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PlagiatonWCF(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PlagiatonWCF(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PlagiatonWCF(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IPlagiatonWCF
     */
    @WebEndpoint(name = "BasicHttpBinding_IPlagiatonWCF")
    public IPlagiatonWCF getBasicHttpBindingIPlagiatonWCF() {
        return super.getPort(BasicHttpBindingIPlagiatonWCF, IPlagiatonWCF.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPlagiatonWCF
     */
    @WebEndpoint(name = "BasicHttpBinding_IPlagiatonWCF")
    public IPlagiatonWCF getBasicHttpBindingIPlagiatonWCF(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIPlagiatonWCF, IPlagiatonWCF.class, features);
    }

}
