
package testCXF.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.7
 * Thu Nov 29 16:18:17 CET 2018
 * Generated source version: 3.2.7
 */

@XmlRootElement(name = "getVersion", namespace = "http://testCXF/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getVersion", namespace = "http://testCXF/")

public class GetVersion {


}

