
package webService.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.7
 * Sat Dec 22 22:16:45 CET 2018
 * Generated source version: 3.2.7
 */

@XmlRootElement(name = "getLiczbaLiniiKoduResponse", namespace = "http://webService/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getLiczbaLiniiKoduResponse", namespace = "http://webService/")

public class GetLiczbaLiniiKoduResponse {

    @XmlElement(name = "return")
    private java.util.LinkedList<classUpload.LiczbaLiniiKodu> _return;

    public java.util.LinkedList<classUpload.LiczbaLiniiKodu> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.LinkedList<classUpload.LiczbaLiniiKodu> new_return)  {
        this._return = new_return;
    }

}

