
package webService.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.7
 * Sun Dec 02 17:50:15 CET 2018
 * Generated source version: 3.2.7
 */

@XmlRootElement(name = "getRozmiaryPlikowKodowResponse", namespace = "http://webService/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRozmiaryPlikowKodowResponse", namespace = "http://webService/")

public class GetRozmiaryPlikowKodowResponse {

    @XmlElement(name = "return")
    private java.util.LinkedList<box.Ziomek> _return;

    public java.util.LinkedList<box.Ziomek> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.LinkedList<box.Ziomek> new_return)  {
        this._return = new_return;
    }

}

