
package webService.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.7
 * Sat Dec 22 21:57:45 CET 2018
 * Generated source version: 3.2.7
 */

@XmlRootElement(name = "nowaMetoda", namespace = "http://webService/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nowaMetoda", namespace = "http://webService/")

public class NowaMetoda {


}

