
package webService.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.7
 * Sun Dec 02 17:50:15 CET 2018
 * Generated source version: 3.2.7
 */

@XmlRootElement(name = "przeslijPlikResponse", namespace = "http://webService/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "przeslijPlikResponse", namespace = "http://webService/")

public class PrzeslijPlikResponse {


}

